### ISSUE TITLE
Quenstion on the CIFAR100-LT performance

### ISSUE THREAD

**Issue by liudakai2** [hyunjunChhoi/Balanced_Energy#1]
Congrats on your wonderful CVPR23 paper!

I am also working on OOD detection research. And I am wondering how your method and the rival "EnergyOE (tune)" achieve such superior performance against PASCL (77% v.s. 73% on AUROC) on CIFAR100-LT? 

Specifically, what is the difference between "EnergyOE (scratch)" and "EnergyOE (tune)"? On CIFAR10-LT and CIFAR100-LT, "EnergyOE (tune)" has already surpassed the SOTA PASCL.

I will be grateful if you can provide some suggestions.

**Comment by hyunjunChhoi** [comment]
(1)Training from scratch 
(2)Fine-tuning based on pre trained model
Pascl is the model training from scratch
Usually OE or EnergyOE model is the model based on the fine-tuning .
They show some different aspects.

**Comment by liudakai2** [comment]
> (1)Training from scratch (2)Fine-tuning based on pre trained model Pascl is the model training from scratch Usually OE or EnergyOE model is the model based on the fine-tuning . They show some different aspects.

Thanks for your comments! What is the "pre-trained model"? Is it a standard ResNet18 classification model trained on CIFAR-LT, for example?

**Comment by hyunjunChhoi** [comment]
> > (1)Training from scratch (2)Fine-tuning based on pre trained model Pascl is the model training from scratch Usually OE or EnergyOE model is the model based on the fine-tuning . They show some different aspects.
> 
> Thanks for your comments! What is the "pre-trained model"? Is it a standard ResNet18 classification model trained on CIFAR-LT, for example?

Yeah that's right

**Comment by liudakai2** [comment]
> > > (1)Training from scratch (2)Fine-tuning based on pre trained model Pascl is the model training from scratch Usually OE or EnergyOE model is the model based on the fine-tuning . They show some different aspects.
> > 
> > 
> > Thanks for your comments! What is the "pre-trained model"? Is it a standard ResNet18 classification model trained on CIFAR-LT, for example?
> 
> Yeah that's right

Thanks a lot. Your work is very insightful and helpful.
