### ISSUE TITLE
question about prior_gamma

### ISSUE THREAD

**Issue by Esther-PAN** [hyunjunChhoi/Balanced_Energy#4]
Hello, thank you for your work. I have some questions that I hope you can help me with while reading the code. 
In Balanced_Energy/classification/inf_train_im_res.py, what does prior_gamma represent? How is it calculated? 
I look forward to your response.

**Comment by hyunjunChhoi** [comment]
> Hello, thank you for your work. I have some questions that I hope you can help me with while reading the code. In Balanced_Energy/classification/inf_train_im_res.py, what does prior_gamma represent? How is it calculated? I look forward to your response.

Oh 

By inferencing whole of 300K (whole auxiliary dataset) into  pretrained model 

we can get the statistics of cardinality of whole samples  which is distribution of prior probablity

But in practice we use more diverse distribution by controlling gamma (  we exponent of gamma) 

if gamma is getting high,  distribution will be more picky    and if it is getting low, distribution will be smooth

if it is 0 then , it is original prior distribution
